Make the build fail when Mutexes are used incorrectly. Breaks the build.
Before this PR, the following code would compile, and would in fact run without obvious errors:
```c++
std::mutex m;
m.lock();
m.unlock();
m.unlock(); // UNDEFINED BEHAVIOR! RACE CONDITIONS! DRAGONS!
```

This type of error is occurring at `client.h` line `340`, where we MAY do a double unlock on
a mutex that was previously unlocked at line `329`. It also happens in `server.h` line `671`.

We happened to spot this issue by code inspection this time, but we should avoid making similar
mistakes in the future.

While `std::mutex` doesn't help us much, Google's `absl::Mutex` will help us catch this class of
error automatically:
* It'll produce a compile-time warning for many types of invalid-mutex-use, including double-lock,
  double-unlock, potential deadlocks, ...; this PR also upgrades those warnings to compile-time
  errors.
* If you manage to avoid the warning and run code that makes such mistakes, it'll crash the program
  instead of silently doing very dangerous things.

This PR...
1. Replaces std::mutex with absl::Mutex.
2. Makes our builds fail if we violate Google's thread safety checks.

Now look at the beautiful errors we get:
```
./stout/grpc/client.h:340:7: error: mutex 'mutex_' is not held on every path through here [-Werror,-Wthread-safety-analysis]
      mutex_.Unlock();
      ^
```

And:
```
./stout/grpc/server.h:671:7: error: mutex 'mutex_' is not held on every path through here [-Werror,-Wthread-safety-analysis]
      mutex_.Unlock();
      ^
```

... That means the build is now broken! Don't worry, we'll only push this commit in a PR that
fixes the issue.